### ISSUE TITLE
YOUR REPO IS PLAGIARISM!!!

### ISSUE THREAD

**Issue by lovebing** [zzzkk2009/react-native-baidu-map#1]
https://github.com/lovebing/react-native-baidu-map

> https://help.github.com/articles/licensing-a-repository/

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

**Comment by xyj0922** [comment]
你的检索功能尽然用的POI检索。。。。

**Comment by zzzkk2009** [comment]
@lovebing 
sorry! i'm very sorry about that!

I'm just want learn to use github.

can i add your repo citation in my repo for license?

**Comment by polyrabbit** [comment]
It's OK, according to the [Wikipedia article](https://en.wikipedia.org/wiki/ISC_license) for ISC license:

> Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

Besides, that repo seems to be died for a long time, if you have time and energy, please continue the development.

**Comment by littleantsos** [comment]
只能呵呵呵呵
